export const costumer_data = [
    {
        id: 1,
        main_result_img: '/costumer_review/1.svg',
        costumer_name: 'Noah',
        costumer_age: '19',
        monthly_income: '4K',
        costumer_region: 'Germany',
        costumer_flag: '/costumer_flag/germany.svg',
        costumer_main_comment: `It was a great experience! I took your YouTube automation course and I'm very satisfied with the results. The content was very comprehensive and easy to understand. I can now manage my YouTube channel more effectively and have noticed a significant increase in my subscribers. I highly recommend this course to everyone. Thank you Daniel`,
        costumer_main_comment_time: '10.12.2023',
        costumer_main_join_time: '24.11.2023',
    },
    {
        id: 2,
        main_result_img: '/costumer_review/2.svg',
        costumer_name: 'Liam',
        costumer_age: '20',
        monthly_income: '2.5K',
        costumer_region: 'Ireland',
        costumer_flag: '/costumer_flag/ireland.svg',
        costumer_main_comment: `I took your YouTube automation course and found it truly impressive. Every stage of the course was meticulously prepared and very instructive. I saw a significant improvement in my channel's performance. Thanks to Daniel and his team!`,
        costumer_main_comment_time: '27.11.2023',
        costumer_main_join_time: '01.11.2023',
    },
    {
        id: 3,
        main_result_img: '/costumer_review/3.svg',
        costumer_name: 'Andrea',
        costumer_age: '17',
        monthly_income: '7.3K',
        costumer_region: 'Italy',
        costumer_flag: '/costumer_flag/italy.svg',
        costumer_main_comment: `This course provided everything I needed to succeed on YouTube. The content was very well structured and easy to understand.`,
        costumer_main_comment_time: '08.09.2023',
        costumer_main_join_time: '17.08.2023',
    },
    {
        id: 4,
        main_result_img: '/costumer_review/4.svg',
        costumer_name: 'Lucas',
        costumer_age: '18',
        monthly_income: '5K',
        costumer_region: 'Netherland',
        costumer_flag: '/costumer_flag/netherland.svg',
        costumer_main_comment: `I completed your YouTube automation course and am very pleased with the results. The course made learning easy by explaining all the processes step by step. Thank you to the team!`,
        costumer_main_comment_time: '07.01.2024',
        costumer_main_join_time: '15.11.2023',
    },
    {
        id: 5,
        main_result_img: '/costumer_review/5.svg',
        costumer_name: 'Lucas',
        costumer_age: '22',
        monthly_income: '12K',
        costumer_region: 'Norway',
        costumer_flag: '/costumer_flag/norway.svg',
        costumer_main_comment: `Thanks to your course, I have made significant progress with my YouTube channel. The content being clear and comprehensive made learning easy. I’ve noticed a visible increase in my subscriber count. Thank you, Daniel and Mark!`,
        costumer_main_comment_time: '07.03.2024',
        costumer_main_join_time: '28.01.2024',
    },
    {
        id: 6,
        main_result_img: '/costumer_review/6.svg',
        costumer_name: 'Jakub',
        costumer_age: '20',
        monthly_income: '8.4K',
        costumer_region: 'Poland',
        costumer_flag: '/costumer_flag/poland.svg',
        costumer_main_comment: `This course provided all the information I needed to grow my YouTube channel. The course materials were very well prepared and clear. I learned the algorithm easily. I highly recommend it to everyone.`,
        costumer_main_comment_time: '19.02.2024',
        costumer_main_join_time: '13.01.2024',
    },
    {
        id: 7,
        main_result_img: '/costumer_review/7.svg',
        costumer_name: 'José',
        costumer_age: '28',
        monthly_income: '8.4K',
        costumer_region: 'Spain',
        costumer_flag: '/costumer_flag/spain.svg',
        costumer_main_comment: `I left my 9-5 job and applied here, and the course content was very well prepared and clear. I learned how the algorithm works easily. Anyone can buy this course`,
        costumer_main_comment_time: '19.02.2024',
        costumer_main_join_time: '13.01.2024',
    },
    {
        id: 8,
        main_result_img: '/costumer_review/8.svg',
        costumer_name: 'Henrik',
        costumer_age: '28',
        monthly_income: '8.4K',
        costumer_region: 'Sweden',
        costumer_flag: '/costumer_flag/sweden.svg',
        costumer_main_comment: `The course made learning easy by explaining all the processes step by step. My channel's performance has noticeably improved. I am grateful to Daniel and John`,
        costumer_main_comment_time: '29.04.2024',
        costumer_main_join_time: '22.02.2024',
    },
    {
        id: 9,
        main_result_img: '/costumer_review/9.svg',
        costumer_name: 'Emily',
        costumer_age: '23',
        monthly_income: '13K',
        costumer_region: 'United Kingdom',
        costumer_flag: '/costumer_flag/uk.svg',
        costumer_main_comment: `I decided to leave my old job and take this course, and I didn't expect it to be this effective. Now, I’m earning twice as much as I did at my previous job, all while working from home and just creating content`,
        costumer_main_comment_time: '08.03.2024',
        costumer_main_join_time: '30.01.2024',
    },

]